### ISSUE TITLE
ReWrite Issue

### ISSUE THREAD

**Issue by pkdhob** [staempfli/magento2-module-rebuild-url-rewrite#4]
I installed module then run below commands but old URL is still there. Can you let me know we need to delete old URL from table "url_rewrite" then run below commands for regenerating new URL

bin/magento urlrewrite:rebuild categories  

bin/magento urlrewrite:rebuild products 

please help.

**Comment by audef1** [comment]
Sorry this repository is no longer maintained by us. Feel free to dig into the code yourself.
